# Generated by Django 6.0.7 on 2026-07-09 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_description_and_more'),
        ('reports', '0002_alter_weeklyreport_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'ordering': ['-week_start', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('user', 'week_start', 'week_end')},
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='week_end',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='week_start',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='blockers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='weekly_reports', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='tasks_completed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='tasks_planned',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='week_start_date',
        ),
    ]
