# Generated by Django 6.0.7 on 2026-07-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_weeklyreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('LATE', 'Late')], default='DRAFT', max_length=20),
        ),
    ]
