# Generated by Django 5.0.6 on 2026-07-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Client A, Internal Tooling, R&D', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief purpose of the project framework', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Allows soft-disabling old categories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
